config/routes.rb
Rails.application.routes.draw do
  mount Upmin::Engine => '/admin'
  devise_for :users
  resources :users
  get 'saved_search_add' => 'searches#saved_search_add', :as => :saved_search_add, :format => :html
  get "home/index"
  get 'apply_search' => 'searches#apply_search', :as => :apply_search, :format => :html
  resources :searches

  authenticated :user do
    root :to => "visitors#authorized_index", :as => "authorized_root"
  end
  root to: 'visitors#index'
  
  resources :portfolios do
    get 'holdings/all/edit' => 'holdings#edit_all', :as => :edit_all
    match 'holdings/all' => 'holdings#update_all', :as => :update_all, :via => :put
    member do
      get 'basic'
      get 'transactions'
    end
    resources :transactions
    resources :holdings do
      get :autocomplete_stock_symbol, :on => :collection
    end
  end

  resources :favorites do
    get :autocomplete_stock_symbol, :on => :collection
    resources :posts
    resources :researches
  end
  
  get 'tags/:tag', to: 'favorites#index', as: :tag

  resources :stocks
  get '/stocks' => 'stocks#index'
  get '/stocks/:id' => 'stocks#show'
  
  resources :reports do
    post 'results' => 'reports#index', :on => :collection
  end
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :favorite
  belongs_to :author, class_name: "User"

  validates :text, presence: true
  scope :persisted, lambda { where.not(id: nil) }
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :stock
  belongs_to :user
  has_many :posts
  has_many :researches
  has_many :attachs, dependent: :destroy
  has_and_belongs_to_many :tags, uniq: true

  validates :user_id, presence: true
  validates :stock_id, presence: true

  def self.tagged_with(name)
    Tag.find_by_name!(name).favorites
  end
  
  def tag_list
    tags.map(&:name)
  end

  def tag_list=(names)
    @tag_list = names
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/holding.rb
class Holding < ActiveRecord::Base
  belongs_to :stock
  belongs_to :portfolio, :inverse_of => :holdings
  validates :stock_id, :portfolio_id, :amount, presence: true
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  belongs_to :user
  has_many :holdings, :inverse_of => :portfolio
  accepts_nested_attributes_for :holdings, allow_destroy: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :favorite
  belongs_to :author, class_name: "User"

  validates :title, presence: true
  validates :post_type, presence: true
  validates :text, presence: true
  scope :persisted, lambda { where.not(id: nil) }
end

app/models/research.rb
class Research < ActiveRecord::Base
  belongs_to :favorite
  belongs_to :user

  has_attached_file :attach,
    styles: lambda { |a| a.instance.attach_content_type.index("image/") == 0 ? { :small => "200x", :original => "600x", :large => "900x" } : {} }
  do_not_validate_attachment_file_type :attach
end

##|attachment| attachment.instance.attach_content_type.index("image/") == 0
##validates_attachment_content_type :attach, :content_type => "image/jpg"
##validates_attachment_file_name :attach, matches: [/png\z/, /jpe?g\z/, /gif\z/, /pdf\z/, /txt\z/, /rtf\z/ ]

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :user

  validates :search_name, presence: true
  validates :user_id, presence: true
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :holdings
  has_many :favorites
  accepts_nested_attributes_for :favorites, allow_destroy: true
  accepts_nested_attributes_for :holdings, allow_destroy: true
  def symbol_with_name
    symbol+", "+company_name
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :favorites
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :favorites, dependent: :destroy
  has_many :portfolios, dependent: :destroy
  has_many :posts
  has_many :researches, dependent: :destroy
  has_many :searches, dependent: :destroy

  def set_default_role
    self.role ||= :user
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :update, :destroy]
  before_action :authenticate_user!
  autocomplete :stock, :symbol, { :display_value => 'symbol_with_name', :full_model => true }

  def index
    if params[:tag]
      @favorites = Favorite.tagged_with(params[:tag])
    else
      @favorites = Favorite.all.order('created_at desc')
    end
  end

  def show
    @post = @favorite.posts.build
  end

  def new
    @favorite = current_user.favorites.new
  end

  def edit
  end

  def create
    @favorite = current_user.favorites.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to favorites_path, notice: 'Favorite was successfully created.' }
        format.json { render :index, location: @favorite }
      else
        format.html { render :new}
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  #def search
  #  if params[:search].present?
  #    @favorite = current_user.favorites.search(params[:search])
  #  else
  #    @favorite = current_user.favorites
  #  end
  #end

  private

  def set_favorite
    unless @favorite = current_user.favorites.where(id: params[:id]).first
      flash[:alert] = 'Favorite not found.'
      redirect_to root_url
    end
  end

  def favorite_params
    params.require(:favorite).permit(:id, :user_id, :stock_id, :symbol, :tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  def tag_links(tags)
    tags.map { |t| link_to t, tag_path(t.strip) }
  end
end

app/helpers/holdings_helper.rb
module HoldingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/reports_helper.rb
require 'net/http'

module ReportsHelper
  module Feature
    class Geturl 
      def self.check_url(url_address)
        begin
          url = URI.parse(url_address)
          req = Net::HTTP.new(url.host, url.port)
          req.use_ssl = (url.scheme == "https")
          res = req.request_head(url.path)
          return res.code
        rescue => e
          puts "Exception: #{e}"
        end
      end
    end
  end
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/favorites/_form.html.erb
<%= simple_form_for(@favorite) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :stock, :url => autocomplete_stock_symbol_favorites_path, :as => :autocomplete, :update_elements => {:id => "#stock_id"}, placeholder: 'Ticker' %>
    <%= f.hidden_field :stock_id, :id => "stock_id" %>
  </div>

  <%= f.label :tag_list, 'Tags (separated by commas)' %>
  <%= f.input :tag_list, as: :string, label: false %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>
  

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Your Favorites</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Company</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <% data = YahooFinance::Client.new.quotes(["#{favorite.stock.symbol}"], [:name]) %>
      <% name = data[0].name %>

      <tr id="favorite_<%= favorite.id %>">
        <td><%= favorite.stock.symbol %></td>
        <td><%= name %></td>
        <% if favorite.tag_list.any? %>
          <td class="tag"><% tag_links(favorite.tag_list).each do |tf| %>
            <span style="background-color:#428bca"><%= raw tf %></span>
          <% end %>
        </td>
      <% end %>
        <td><%= link_to 'Research', favorite_researches_path(favorite) %></td>  
        <td><%= link_to 'Message Board', favorite_posts_path(favorite) %></td>
        <td><%= link_to 'Delete', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Favorite', new_favorite_path, :id => "open-contacts-dialog-btn", 
  :class => "inbox-sf-add-btn tip", :method => :get %>

app/views/favorites/new.html.erb
<h1>New Favorites</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @favorite.stock.symbol%>
  </p>
  
<div id="posts">
  <% if @favorite.posts.any? %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>MSG #</th>
          <th>SUBJECT</th>
          <th>TYPE</th>
          <th>SENTIMENT</th>
          <th>AUTHOR</th>
          <th>DATE POSTED</th>
        </tr>
      </thead>

      <tbody>
        <% @favorite.posts.each do |post| %>
          <tr>
            <td><%= post.id %></td>
            <td class="blue">
              <%= link_to [@favorite, post] do %>
                <%= post.title %>
              <% end %>
            </td>
            <td><%= post.post_type %></td>
            <td><%= post.sentiment %></td>
            <td><%= post.author.email unless post.author.nil? %></td>
            <td><%= post.created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>There are no posts for this favorite.</p>
  <% end %>
</div>

<%= button_to "Add Post", new_favorite_post_path(@post.favorite, @post), :class => "button", :method => :get %>
<div>
  <%= link_to 'Back', favorites_path %>
</div>
    