config/routes.rb
Rails.application.routes.draw do
  mount Upmin::Engine => '/admin'
  devise_for :users
  resources :users
  get 'saved_search_add' => 'searches#saved_search_add', :as => :saved_search_add, :format => :html
  get "home/index"
  get 'apply_search' => 'searches#apply_search', :as => :apply_search, :format => :html
  resources :searches

  authenticated :user do
    root :to => "visitors#authorized_index", :as => "authorized_root"
  end
  root to: 'visitors#index'
  
  resources :portfolios do
    get 'holdings/all/edit' => 'holdings#edit_all', :as => :edit_all
    match 'holdings/all' => 'holdings#update_all', :as => :update_all, :via => :put
    member do
      get 'basic'
      get 'transactions'
    end
    resources :transactions
    resources :holdings do
      get :autocomplete_stock_symbol, :on => :collection
    end
  end

  resources :favorites do
    get :autocomplete_stock_symbol, :on => :collection
    resources :posts
    resources :researches
  end
  
  get 'tags/:tag', to: 'favorites#index', as: :tag

  resources :stocks
  get '/stocks' => 'stocks#index'
  get '/stocks/:id' => 'stocks#show'
  
  resources :reports do
    post 'results' => 'reports#index', :on => :collection
  end
  
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  belongs_to :user
  has_many :holdings, :inverse_of => :portfolio
  accepts_nested_attributes_for :holdings, allow_destroy: true
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  autocomplete :stock, :symbol
  respond_to :html, :js

  def index
    @portfolios = current_user.portfolios.order('created_at desc')
  end

  def show
    @portfolios = current_user.portfolios.where.not(id: params[:id]).order('created_at desc')
    @holdings = @portfolio.holdings.select(:stock_id).
      select(@portfolio.holdings.arel_table[:amount].sum.as("total_sum")).select(%q{sum(case when position = 'Buy' then amount else 0 end) as sum_buy}).select(%q{sum(case when position = 'Sell' then amount else 0 end) as sum_sell}).select(%q{sum(case when position = 'Buy' then amount*trade_price else 0 end) as total_buy}).select(%q{sum(case when position = 'Sell' then amount*trade_price else 0 end) as total_sell}).group(:stock_id)
  end

  def new
    @portfolio = current_user.portfolios.new
    @portfolio.holdings.build
  end

  def edit
    @portfolio = current_user.portfolios.find(params[:id])
    @portfolio.holdings.build
  end

  def create
    @portfolio = current_user.portfolios.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.js
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def basic
    @portfolio = current_user.portfolios.find(params[:id])
    @holdings = @portfolio.holdings.select(:stock_id).
      select(@portfolio.holdings.arel_table[:amount].sum.as("total_sum")).select(%q{sum(case when position = 'Buy' then amount else 0 end) as sum_buy}).select(%q{sum(case when position = 'Sell' then amount else 0 end) as sum_sell}).select(%q{sum(case when position = 'Buy' then amount*trade_price else 0 end) as total_buy}).select(%q{sum(case when position = 'Sell' then amount*trade_price else 0 end) as total_sell}).group(:stock_id)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def transactions
    @portfolio = current_user.portfolios.find(params[:id])
    @holdings = @portfolio.holdings.order('created_at desc')
    respond_to do |format|
      format.js
    end
  end

  def detailed
    @portfolio = current_user.portfolios.find(params[:id])
    @holdings = @portfolio.holdings.order('created_at desc')
    respond_to do |format|
      format.js
    end
  end

  private

  def set_portfolio
    unless @portfolio = current_user.portfolios.where(id: params[:id]).first
      flash[:alert] = 'Portfolio not found.'
      redirect_to root_url
    end
  end

  def portfolio_params
    params.require(:portfolio).permit(:user_id, :name, holdings_attributes: [:id, :stock, :amount, :stock_id, :user_id, :date_purchased, :trade_price])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= simple_form_for @portfolio, :remote => request.xhr? do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <button id="new-cancel-btn" class="btn btn-default cancel-btn">Cancel</button>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<tr id="portfolio_<%= portfolio.id %>">
  <td><%= link_to portfolio.name, portfolio %></td>
  <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
  <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/portfolios/basic.js.erb
$('#removable').html('<%= j render partial: "holdings/view_basic" %>');
$('ul.nav-tabs li.active').removeClass('active')
$('#basic').parent('li').addClass('active')
$("td.currency").each(function() {
  var text = $(this).text();
  var num = parseFloat(text);
  if (num < 0) {
    $(this).addClass("negative");
  } else if (num > 0) {
    $(this).addClass("positive");
  }
});

app/views/portfolios/create.js.erb
$('#new_portfolio').remove();
$('#new_portfolio_link').show();
$('#portfolio').prepend('<% j render("portfolio", :portfolio => @portfolio) %>');

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form' %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Your Portfolio</h3>

<%= link_to new_portfolio_path, remote: true, :id => "new_portfolio_link" do %>
  <button type="button" class="btn btn-default">New Portfolio</button>
<% end %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="portfolios">
    <% @portfolios.each do |portfolio| %>
      <%= render "portfolio", :portfolio => portfolio %>
    <% end %>
  </tbody>
</table>

<br>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form' %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/new.js.erb
$('#new_portfolio_link').hide().after('<%= j render("form") %>');
$('#portfolio_name').focus();
$(".cancel-btn").click(function(evt) {
  $('#new_portfolio_link').show();
  evt.preventDefault();
  return $(this).closest("#new_portfolio").hide();
});

app/views/portfolios/show.html.erb
<h4>Dashboard: <%= @portfolio.name %></h4>

<ul class="nav nav-pills">
  <li><%= link_to 'Add/Edit Holdings', portfolio_edit_all_path(@portfolio) %></li>
  <li><%= link_to 'View All Portfolios', portfolios_path %></li>
  <li class="dropdown hover">
  <a href="#" data-toggle="dropdown" class="dropdown-toggle">
    Portfolios<b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li class="disabled"><%= link_to @portfolio.name, @portfolio %></li>
    <% @portfolios.each do |portfolio| %>
      <li><%= link_to portfolio.name, portfolio %></li>
    <% end %>
  </ul>
  </li>
  <li class="dropdown pull-right">
  <a href="#" data-toggle="dropdown" class="dropdown-toggle">Settings <b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><%= link_to 'Edit', edit_portfolio_path(@portfolio) %></li>
    <li><a href="#">Another action</a></li>
    <li class="divider"></li>
    <li><a href="#">Settings</a></li>
  </ul>
  </li>
</ul>
<p></p>
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><%= link_to "Basic", {:controller => "portfolios", :action => "basic"}, id: 'basic', :remote => true %></li>
  <li role="presentation"><%= link_to "Transactions", {:controller => "portfolios", :action => "transactions"}, id: 'transactions', :remote => true %></li>
</ul>

<%= render "/holdings/view_basic" %>

<%= link_to '[+] Add Stock', new_portfolio_holding_path(@portfolio), remote: true, :id => "new_holding_link" %>

app/views/portfolios/transactions.js.erb
$('#removable').html('<%= j render partial: "holdings/view_transactions" %>');
$('ul.nav-tabs li.active').removeClass('active')
$('#transactions').parent('li').addClass('active')
$("td.currency").each(function() {
  var text = $(this).text();
  var num = parseFloat(text);
  if (num < 0) {
    $(this).addClass("negative");
  } else if (num > 0) {
    $(this).addClass("positive");
  }
});